# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            blueCFD-Core Project
tagline:          'Enabling native use of OpenFOAM&reg; for Windows'
description:      'Bringing OpenFOAM&reg; technology to Windows.'
url:              blueCFD.github.io
baseurl:          http://blueCFD.github.io/Core/

author:
  name:           'blueCAPE Lda'
  url:            http://www.bluecape.com.pt
  email:          http://bluecfd.com/contact

paginate:         3
paginate_path:    "http://blueCFD.github.io/Core/News/page:num/"

# Custom vars
version:          2016-1

github:
  repo:           https://github.com/blueCFD/Core
