# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            blueCFD-Core Project
tagline:          'Enabling native use of OpenFOAM&reg; for Windows'
description:      'Bringing OpenFOAM&reg; technology to Windows.'
url:              blueCFD.github.io
baseurl:          /Core

author:
  name:           'blueCAPE Lda'
  url:            http://blueCFD.github.io/Core
  email:          http://bluecfd.com/contact

paginate:         3

# Custom vars
version:          2016-1

github:
  repo:           https://github.com/blueCFD/Core
